### ISSUE TITLE
fi-tampere: Processing fails

### ISSUE THREAD

**Issue by jbruechert** [public-transport/transitous#153]
```
Error while parsing GTFS feed:
Could not open required file agency.txt
Parsing GTFS feed in '/transitous/downloads/fi_tampere.gtfs.zip' ...
You may want to try running gtfstidy with --fix for error fixing / skipping. See --help for details.
```

Please consider removing or replacing the feed.

@vkrause

**Comment by vkrause** [comment]
Can't reproduce locally, I get a valid feed here. Could be them blocking Github downloads though, I needed to add a manual User Agent header to make that work in the first place, otherwise it was returning unclear errors and HTML content. Surprising it got through the PR pipeline then though.
