### ISSUE TITLE
MOTIS crashes at import once again

### ISSUE THREAD

**Issue by jbruechert** [public-transport/transitous#163]
Needs someone to debug this locally

**Comment by felixguendling** [comment]
I wanted to check and tried `rsync` but the server seems to be down.

```
rsync -rav --progress routing.spline.de::transitous transitous
rsync: [Receiver] failed to connect to routing.spline.de (130.133.110.91): Connection refused (111)
rsync: [Receiver] failed to connect to routing.spline.de (2001:470:51c5:babe::91:1): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(139) [Receiver=3.2.7]
```

Or maybe you know already which dataset causes it and you have a download link?

**Comment by vkrause** [comment]
No luck here either with the rsync'ed state, neither on startup nor during a full GTFS-RT update cycle. Built with clang 16, without ASAN (ASAN fails with the HTTP client code, so trying with that only makes sense if the crash happens during startup/import).

**Comment by felixguendling** [comment]
> My local MOTIS is built using gcc though

The MOTIS release is also built with GCC. The toolchain is built in this repository: https://github.com/motis-project/musl-toolchains

Did you enable mimalloc?
https://github.com/motis-project/motis/blob/master/CMakePresets.json#L63-L64

**Comment by felixguendling** [comment]
> No luck here either with the rsync'ed state, neither on startup nor during a full GTFS-RT update cycle. Built with clang 16, without ASAN (ASAN fails with the HTTP client code, so trying with that only makes sense if the crash happens during startup/import).

Did you use the [`linux-asan` preset](https://github.com/motis-project/motis/blob/6c30f88ba5ffb36284958517ea46822681fba97b/CMakePresets.json#L154) or manually set `-DCTX_ASAN=On`? If yes, did you store the stacktrace by chance?
