### ISSUE TITLE
Generate license page

### ISSUE THREAD

**Issue by jbruechert** [public-transport/transitous#18]
We can now generate a license summary as json using `./src/generate-attribution.py`.
In order to make it easy for apps to link to it, we should set up a static site generator to make this data more readable for humans.

**Comment by PartTimeDataScientist** [comment]
As all the CI/CD runs on GH actions the most straighforward option would be to use Github Pages for the license summary. We could simply generate an AsciiDoc Document in the script instead / in addition to the json and render that for Github Pages.
