### ISSUE TITLE
Create a website

### ISSUE THREAD

**Issue by jbruechert** [public-transport/transitous#29]
Approximate contents:
* Very short description of the service / slogan
* A search field to try our routing, should just forward the request to the motis web interface. This may need extending motis with query parameters for this purpose. Maybe a simplified version of what https://www.vy.no/en#journey-planner does
* Further down some API example, link to motis docs / our docs in case we have some by then.

**Comment by PartTimeDataScientist** [comment]
The rendering of the website ist done in the Github actions. The gh-pages branch does not contain a docs folder at all...

**Comment by PartTimeDataScientist** [comment]
If you set this up to deploy I think Github is trying to render a Jekyll site. We are talking about option 3 of this tutorial:

https://roelofjanelsinga.com/articles/how-to-set-up-automatically-deploy-website-github-pages/

**Comment by PartTimeDataScientist** [comment]
> Oh sorry, I misread that as deploying the contents of the branch to /docs, changed it to / now. It's probably relatively easy to move to /docs, right?
> 
> I'd like to do something else for the front page in the future.

That worked, website is now available under the links from the README. A better front page should be easy to integrate:

In the front matter of your index.md, you need to specify the template to use:

```
---
title: Title
template: home.html
---
```
Source: https://stackoverflow.com/questions/63438788/how-to-add-a-landing-page-to-a-mkdocs-doc-site-using-mkdocs-material)
