### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by jbruechert** [public-transport/transitous#393]
I couldn't find anything suspicious in the log so far. Unfortunately the log is multiple GB big, so I can't attach it here.

It could be that we are out of memory, but I allocated 4 more GB without fixing the problem.

Next step would probably to try to reproduce it locally.

**Comment by felixguendling** [comment]
> Next step would probably to try to reproduce it locally.

Would be great to run it directly with `gdb` (maybe even with `catch throw`) to see where it has problems.
I can also try to sync with the transitous dataset next week and check what's going on.
