### ISSUE TITLE
MOTIS: Implement support for mode filtering

### ISSUE THREAD

**Issue by jbruechert** [public-transport/transitous#46]
The Norway dataset contains flights, which make it impossible to find train connections there because they are always faster.

We need to be able to filter those out.

**Comment by derhuerst** [comment]
Personally, I wouldn't necessarily want to filter those out, but rather expand the set of Pareto criteria so that they appear alongside train/bus connections, with all their trade-offs.

**Comment by felixguendling** [comment]
My guess: performance is better if you just start two separate searches, one with flights allowed, one with flights not allowed and then merge them to become one Pareto-set. Different approach, same results, better performance for the user (and no significant changes to the actual routing algorithm).

**Comment by felixguendling** [comment]
Implemented here:

https://github.com/motis-project/motis/pull/453
https://github.com/motis-project/motis/releases/tag/v0.11.21

My guess is that you can produce long running queries by enabling only local bus usage and routing through Europe.

**Comment by felixguendling** [comment]
I guess this can be closed.
