### ISSUE TITLE
GTFS-RT realtime update fetching

### ISSUE THREAD

**Issue by vkrause** [public-transport/transitous#5]
That's not done by MOTIS itself, it expects downloads to happen externally and then be notified about new data. That makes sense given the access to those feeds isn't standardized and can e.g. need additional authorization headers.

So we also need to build that, basically https://github.com/motis-project/motis/blob/master/modules/ris/crawl_swiss_gtfs_rt.sh in big:
* configured by the same form of per-feed metadata as used for the static data
* needs to run at a high-frequency (~60secs), so probably has to be on the MOTIS machine itself
* given the amount of feeds some will likely not always respond promptly, so this needs to be happen parallelized and with aggressive timeouts.
* this needs some form of monitoring and error reporting for persistent feed update failures
* needs to make sure that MOTIS doesn't get confused by partial/still ongoing downloads, e.g. by making fully downloaded files available atomically by a rename.

**Comment by 1Maxnet1** [comment]
Little note regarding real-time feeds: As far as I know, the new core called nigiri is not yet capable to consume real-time information / the real-time module is not yet updated to be compatible with the new core: https://github.com/motis-project/motis/wiki/Modules#modules-compatible-to-the-new-core. However, when the deployment should span whole Europe, Transitous probably should use the new core, to keep the hardware requirements in a feasible manner. It might be worth it to express interest at the MOTIS repository so the developers can comment what the current state there is.

**Comment by vkrause** [comment]
Turns out that is all the old system apparently, Nigiri has GTFS-RT retrieval built-in and that does work without needing more than a config line per feed.
