### ISSUE TITLE
Add RT Feed for BE-tec

### ISSUE THREAD

**Issue by eMerzh** [public-transport/transitous#558]
Hello 👋 
Thanks for maintaining this, 
it seems that transitland have just added the RT version of tec

https://github.com/transitland/transitland-atlas/pull/1263

new id is "f-u0g-tec~rt" ... not 100% sure how to add it, but i would be happy to help if i can

**Comment by jbruechert** [comment]
Hi! Nice to hear that there are more GTFS-RT feeds available.
You can add it after the static timetable in this file: https://github.com/public-transport/transitous/blob/main/feeds/be.json#L39.
The realtime entry needs to have the same name, so they can be matched together.

You can use this as an example: https://github.com/public-transport/transitous/blob/main/feeds/hr.json#L21-L30
