### ISSUE TITLE
Motis wrong trip duration, missing 24h

### ISSUE THREAD

**Issue by Altonss** [public-transport/transitous#601]
See https://routing.spline.de/?motis=https%3A%2F%2Frouting.spline.de%2Fapi#/trip/us-Amtrak_85643/us-Amtrak_CHI/5/1730923200/us-Amtrak_EMY/1731113820/

**Comment by felixguendling** [comment]
Thanks, there was an issue with the duration in MOTIS v2 too. This is fixed in MOTIS v2 which will be available soon.
